import { generateEpub } from '../actions';

export interface ExportConfig {
    title: string;
    author: string;
    subject?: string;
    language?: string;
    copyright?: string;
    foreword?: string;
    afterword?: string;
    includeTOC?: boolean;
}

export interface ChapterData {
    title: string;
    content: string;
    id: string;
}

const generateHtmlContent = (chapters: ChapterData[], config: ExportConfig) => {
    let html = `
    <html>
    <head>
        <style>
            body { font-family: serif; color: black; line-height: 1.6; }
            h1 { page-break-before: always; text-align: center; margin-bottom: 2rem; color: #333; }
            p { margin-bottom: 1rem; text-indent: 1.5em; }
            .copyright-page { page-break-after: always; display: flex; flex-direction: column; justify-content: center; height: 90vh; text-align: center; font-size: 0.8rem; }
            .toc { page-break-after: always; }
            .toc-item { margin-bottom: 0.5rem; }
            .foreword, .afterword { page-break-after: always; }
            .title-page { height: 90vh; display: flex; flex-direction: column; justify-content: center; align-items: center; page-break-after: always; }
            .book-title { font-size: 3rem; font-weight: bold; margin-bottom: 1rem; }
            .book-author { font-size: 1.5rem; font-style: italic; }
        </style>
    </head>
    <body>
    `;

    html += `
        <div class="title-page">
            <div class="book-title">${config.title}</div>
            <div class="book-author">${config.author}</div>
        </div>
    `;

    if (config.copyright) {
        html += `
            <div class="copyright-page">
                <p>${config.copyright}</p>
                <p>Generated by Bread</p>
            </div>
        `;
    }

    if (config.includeTOC) {
        html += `
            <div class="toc">
                <h1>Table of Contents</h1>
                ${chapters.map((c) => `<div class="toc-item">${c.title}</div>`).join('')}
            </div>
        `;
    }

    if (config.foreword) {
         html += `
            <div class="foreword">
                <h1>Foreword</h1>
                ${config.foreword}
            </div>
         `;
    }

    chapters.forEach(c => {
        html += `
            <h1>${c.title}</h1>
            ${c.content}
        `;
    });

     if (config.afterword) {
         html += `
            <div class="afterword">
                <h1>Afterword</h1>
                ${config.afterword}
            </div>
         `;
    }

    html += '</body></html>';
    return html;
};

export const exportToPdf = async (chapters: ChapterData[], config: ExportConfig) => {
    const htmlContent = generateHtmlContent(chapters, config);
    const opt = {
        margin: 1,
        filename: `${config.title.replace(/\s+/g, '_')}.pdf`,
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' as const }
    };

    const html2pdf = (await import('html2pdf.js')).default;
    html2pdf().set(opt).from(htmlContent).save();
};

export const exportToEpub = async (chapters: ChapterData[], config: ExportConfig) => {
   const epubOptions = {
       title: config.title,
       author: config.author,
       publisher: "Bread",
       version: 3,
       css: `body { font-family: serif; } h1 { text-align: center; } p { margin-bottom: 1em; }`,
   };

   try {
       const contentArray = [
           ...(config.foreword ? [{ title: "Foreword", content: config.foreword }] : []),
           ...chapters.map(c => ({ title: c.title, content: c.content })),
           ...(config.afterword ? [{ title: "Afterword", content: config.afterword }] : [])
       ];
       
       const base64 = await generateEpub(epubOptions, contentArray);
       
        const binaryString = window.atob(base64);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }
        const epubBlob = new Blob([bytes], { type: "application/epub+zip" });

       const link = document.createElement('a');
       link.href = URL.createObjectURL(epubBlob);
       link.download = `${config.title.replace(/\s+/g, '_')}.epub`;
       document.body.appendChild(link);
       link.click();
       document.body.removeChild(link);
       
   } catch (e) {
       console.error("EPUB Generation failed", e);
       alert("Failed to generate EPUB. See console.");
   }
};

export const exportToMarkdown = (chapters: ChapterData[], config: ExportConfig) => {
    let md = `# ${config.title}\n\nBy ${config.author}\n\n`;
    
    if(config.copyright) md += `\n> ${config.copyright}\n\n---\n\n`;
    
    if(config.foreword) md += `## Foreword\n\n${config.foreword}\n\n---\n\n`;
    
    chapters.forEach(c => {
        md += `## ${c.title}\n\n${c.content}\n\n`;
    });
    
    if(config.afterword) md += `\n---\n\n## Afterword\n\n${config.afterword}\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${config.title.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};
